# Generated by Django 3.2.6 on 2021-08-20 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20210820_0040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='time',
            old_name='date',
            new_name='user',
        ),
    ]
