# Generated by Django 3.2.6 on 2021-08-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_rename_date_time_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='has_texted',
            field=models.BooleanField(default=False),
        ),
    ]
