# Generated by Django 3.2.6 on 2021-08-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20210820_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_read',
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nhs_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='postal_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='time',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Time',
        ),
    ]
