# Generated by Django 3.2.6 on 2021-08-24 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20210824_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='message',
        ),
    ]
