# Generated by Django 3.2.6 on 2021-08-31 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_remove_user_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255, null=True)),
                ('postal_code', models.CharField(max_length=100, null=True)),
                ('nhs_number', models.CharField(max_length=255, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('date', models.DateField()),
                ('has_texted', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='Public',
        ),
    ]
