# Generated by Django 3.2.6 on 2021-09-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20210831_1418'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('is_open', models.BooleanField(default=False)),
            ],
        ),
    ]
