# Generated by Django 3.2.6 on 2021-09-11 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_admintasks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminTasks',
            new_name='AdminTask',
        ),
    ]
