# Generated by Django 3.2.6 on 2021-09-11 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_rename_admintasks_admintask'),
    ]

    operations = [
        migrations.AddField(
            model_name='admintask',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
