# Generated by Django 3.2.6 on 2021-09-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_admintask_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='admintask',
            name='pharmacy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='public',
            name='pharmacy',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
