# Generated by Django 3.2.6 on 2021-09-20 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_alter_public_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public',
            name='time',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
