# Generated by Django 3.2.6 on 2021-09-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_alter_public_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='public',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='workplace',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='workplace',
            name='pharmacy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='public',
            name='time',
            field=models.TimeField(max_length=255, null=True),
        ),
    ]
