# Generated by Django 3.2.6 on 2021-09-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_auto_20210922_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public',
            name='number',
            field=models.IntegerField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workplace',
            name='number',
            field=models.IntegerField(max_length=255, null=True),
        ),
    ]
