# Generated by Django 3.2.6 on 2021-09-25 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_auto_20210924_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='public',
            name='number',
        ),
        migrations.RemoveField(
            model_name='workplace',
            name='number',
        ),
    ]
