# Generated by Django 3.2.6 on 2021-09-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_auto_20210925_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='admintask',
            name='number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='public',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
